# butun profiller icin ortak ayarlar
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html
spring.flyway.enabled=true

# Gelistirme ortaminda hangi profilin aktif olacagini belirtir
spring.profiles.active=dev-h2

# Canli ortam (Render) icin varsayilan disk ayari prod ta var burdan kaldirilabilir
file.upload-dir=/var/data/uploads 

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB